easy_admin:
    design:
      menu:
        - {label: "Home", icon: 'home', url: '/'}
        - {label: "Entities"}
        - label: "Movies" 
          icon: "film"
          children:
            - {entity: Movie, label: "Movies List", icon: "th-list"}
            - {entity: Movie, label: "Add Movie", icon: "plus", params: {action: 'new'}}
        - label: "Favorite Lists" 
          icon: "star"
          children:
            - {entity: MoviesList, label: "Lists", icon: "th-list"}
            - {entity: MoviesList, label: "Create List", icon: "plus", params: {action: 'new'}}
        - {label: "Settings"}
        - label: "Users" 
          icon: "user"
          children:
            - {entity: User, label: "User List", icon: "th-list"}
    site_name: '<h1>Admin Page</h1>'
    user:
      display_name: true
      display_avatar: true
      name_property_path: 'Username'
    entities:
        # List the entity class name you want to manage
        User:
          class: App\Entity\User
          disabled_actions: ['new']
          edit:
            fields:
              - Username
              - email
              
        Movie:
          class: App\Entity\Movie
          list:
            fields:
                    - title
                    - { property: 'image', type: 'image' }
          #form:
           # fields:
            #   - title
             #  - { property: 'imageFile', type: 'vich_image' }
        MoviesList:
          class: App\Entity\MoviesList
        
